// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.DataLayerEF.Database;

namespace WebApi.DataLayerEF.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201110153437_InitialModel")]
    partial class InitialModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WebApi.DomainLayer.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUri")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(11,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "obyčejná lampa",
                            ImgUri = "http://127.0.0.1/lampa.jpg",
                            Name = "Lampa",
                            Price = 299.50m
                        },
                        new
                        {
                            Id = 2,
                            Description = "neobyčejný stůl",
                            ImgUri = "http://127.0.0.1/stul.jpg",
                            Name = "Stůl",
                            Price = 699.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "skvělá skříň",
                            ImgUri = "http://127.0.0.1/skrin.jpg",
                            Name = "Skříň",
                            Price = 1611.50m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
